### ISSUE TITLE
Design for dark mode

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/theoutlet#40]

**Comment by kikipluche** [comment]
@david-gauquelin You created  the dark mode for milestone one, is this an issue you want to keep for the next milestones, or can i close it?

**Comment by david-gauquelin** [comment]
You can close it, if we decide to implement dark mode then I will simply reuse this style with the new design (and create another card)

**Comment by kikipluche** [comment]
ok, I think Vojtech already did the dark mode, it is in the vercell app.... I'll ask next meeting what the intend is.
